### PR TITLE
Add pl translation

### PR DESCRIPTION
**Pull request by monsterdream**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
You did it !! good job :+1: 

And thanks again, @monsterdream.

**Comment by monsterdream** [comment]
Thank you, Thank you :D That was my first time when I helped somebody else on GitHub that why I was little bit lost ;) But you welcome and Happy New Year :)

**Comment by arcanedev-maroc** [comment]
Happy New Year @monsterdream :tada:.

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Comment by monsterdream** [comment]
Of course, just give me a while and it will be done. Ask me when ever 
you will need my help.

Best regards,
Filip Kostrzewski

**Comment by arcanedev-maroc** [comment]
Great, thanks a lot @monsterdream 👍

**Pull request merged**
