### PR TITLE
Complete Armenian and Russian translations

### PR DESCRIPTION
**Pull request by VahanMargaryan**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thanks for your PR @VahanMargaryan 👍 

Can you skip the `.gitignore` commit ? Because it's highly recommended (best practice) you do it in your **global .gitignore**.

Source: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by VahanMargaryan** [comment]
It's done, I've skipped last commit

**Comment by arcanedev-maroc** [comment]
Nice @VahanMargaryan , last thing to do is to remove all the `.DS_Store` files.

Try this command (i've just googled it) : `git ls-files | grep '\.DS_Store$' | xargs git rm -f`

**Comment by VahanMargaryan** [comment]
Thanks, I know how to find files and remove it via console, but in this project already has .DS_Stoe files ;)

**Comment by arcanedev-maroc** [comment]
No, the .DS_Store files exists only in your PR.

You can [check the changed files](https://github.com/ARCANEDEV/LogViewer/pull/100/files) (5 files in total instead of 2).

**Pull request merged**
