### PR TITLE
Add Traditional Chinese Translation (zht)

### PR DESCRIPTION
**Pull request by vongola12324**
Add Traditional Chinese Translation (zht)

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Hi @vongola12324, thanks for your contribution :+1: 

Can you [add your locale at this line](https://github.com/ARCANEDEV/LogViewer/blob/master/tests/TestCase.php#L29) ?

**Comment by vongola12324** [comment]
Hi, I have already added it. :smile:

**Comment by arcanedev-maroc** [comment]
Great ( ^_^)b

**Comment by arcanedev-maroc** [comment]
Did you know how to rebase all these commits ?

**Comment by vongola12324** [comment]
Oh, Ummm....
Did you mean this?

**Comment by arcanedev-maroc** [comment]
Yes, it means squash all the commits to keep the history clean.

Thanks

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Comment by vongola12324** [comment]
I'm sorry too late to see this message.
I will finish the translation as soon as possible.

**Comment by arcanedev-maroc** [comment]
Take your time, no rush 😉 

and also thank you very much for your help 👍

**Comment by vongola12324** [comment]
Done. #116 😄

**Pull request merged**
