### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by bobbybouwmann**

### CODE REVIEW

**Comment by bobbybouwmann** [comment]
Done ;)

**Comment by arcanedev-maroc** [comment]
Cool ( ^_^)b

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Comment by bobbybouwmann** [comment]
Will do ;)

**Comment by arcanedev-maroc** [comment]
Thanks a lot @bobbybouwmann 👍

**Pull request merged**
