### PR TITLE
Added Chinese Simplified translation (zh)

### PR DESCRIPTION
**Pull request by arrowrowe**

### CODE REVIEW

**Comment by arrowrowe** [comment]
Tests for PHP 7 failed because of installation.

Looking into this......

**Comment by arcanedev-maroc** [comment]
It's OK, you've done a great job. Thanks :+1: 

I think the issue is on Travis or AWS.

I will merge it soon.

**Comment by arrowrowe** [comment]
It's a pleasure. :smile:

Quite strange though. Maybe we should try `sudo: required` for `.travis.yml`?......

**Comment by arcanedev-maroc** [comment]
Check this : https://github.com/travis-ci/travis-ci/issues/5111

**Comment by arrowrowe** [comment]
Thanks! That's it.

**Comment by arrowrowe** [comment]
Hey @arcanedev-maroc, do you think I should name it `zh_CN` instead of `zh-CN`?

Symfony has `zh_CN` (see [here](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Resources/translations/security.zh_CN.xlf)).

This is the first translation here with a suffix. :p

**Comment by arcanedev-maroc** [comment]
Why not `zh` ??

https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L1828

**Comment by arrowrowe** [comment]
It's OK as well. On it.

**Comment by arcanedev-maroc** [comment]
@arrowrowe I've merged your PR, thanks again :+1:

**Comment by arrowrowe** [comment]
My pleasure :stuck_out_tongue_closed_eyes:

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Comment by arcanedev-maroc** [comment]
Cool, thanks @arrowrowe 👍

**Pull request merged**
