### PR TITLE
Translation german.

### PR DESCRIPTION
**Pull request by Schnoop**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thanks ( ^_^)b

**Comment by arcanedev-maroc** [comment]
@Schnoop 

Add 'de' after 'ar' at : https://github.com/ARCANEDEV/LogViewer/blob/master/tests/TestCase.php#L32

**Comment by Schnoop** [comment]
Done.

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Pull request merged**
