### PR TITLE
Page load speed improve

### PR DESCRIPTION
**Pull request by zorn-v**
With many log files log view take minimum 5 sec to load, because even you need only one log it reads ALL.

PS. Will be nice if this change backported to older versions of package

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Hi @zorn-v, thanks for the contribution :+1: 

Can you try to do these changes inside `Arcanedev\LogViewer\Utilities\Factory` instead ?

The LogViewer class is just like a wrapper for these utilities

**Comment by zorn-v** [comment]
Yea, I just copied from my class that extends LogViewer and registered as singleton in my app. 
I use LogViewer facade to build (get dates) "select another log" in show log view

**Review by arcanedev-maroc — APPROVED** [review]

**Comment by arcanedev-maroc** [comment]
LGTM, the tests are green

Just give me some time to test these changes to make sure there is no breaking changes

Thanks again :+1:

**Review by kylekatarnls — APPROVED** [review]

**Comment by zorn-v** [comment]
Is it will be merged sometime ?

**Comment by zorn-v** [comment]
@arcanedev-maroc ?

**Review by ahmedmansour08 — APPROVED** [review]

**Pull request merged**
