### PR TITLE
added Romanian translation

### PR DESCRIPTION
**Pull request by tabacitu**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thank you for contributing to this package, but you've forgot to read the [Contribution Guidelines](https://github.com/ARCANEDEV/LogViewer/blob/master/CONTRIBUTING.md).

**Comment by arcanedev-maroc** [comment]
Nice job :+1: .

**Comment by tabacitu** [comment]
Sorry, I missed that. Cheers!

**Comment by arcanedev-maroc** [comment]
No problem :smile:

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Pull request merged**
