### PR TITLE
[Front] Add search support (only the entry's header)

### PR DESCRIPTION
**Pull request by uicosp**
Use laravel collection "filter" method to achieve "search" feature. It may not efficient, just work. And I'm not good at CSS, hope someone can make it looker better.

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thank for the great job 👍 

Don't worry about the design, i'm going to make it prettier ✨

**Comment by uicosp** [comment]
Looking forward to the prettier search bar 😉

**Comment by arcanedev-maroc** [comment]
You got it #153 🔥

**Comment by uicosp** [comment]
nice!

**Pull request merged**
