### PR TITLE
Swedish (sv) localization

### PR DESCRIPTION
**Pull request by blomdahldaniel**
Hi! I added a Swedish localization for the project.

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thanks @blomdahldaniel,

Can you add `sv` after `nl` at : https://github.com/ARCANEDEV/LogViewer/blob/master/tests/TestCase.php#L29

**Comment by blomdahldaniel** [comment]
Sorry about that, maybe you could add a *Localizations* section in your [CONTRIBUTING.md](https://github.com/ARCANEDEV/LogViewer/blob/master/CONTRIBUTING.md) where you inform that added language should also pushed added to that array?

**Comment by arcanedev-maroc** [comment]
Yep, you're right about that.

**Comment by arcanedev-maroc** [comment]
Good work @blomdahldaniel, thanks again.

**Comment by blomdahldaniel** [comment]
I am glad to be able to contribute to such a lovely project! :smiley: 
Great job! :+1:

**Comment by arcanedev-maroc** [comment]
Can you please help me to translate this one ?

Issue: #95

**Pull request merged**
