### PR TITLE
Fix bugs created in #153

### LINKED ISSUE #234: [PHP 7.3] compact() issues an E_NOTICE level error
- LogViewer Version: 4.6.0
- Laravel Version: 5.7.2
- PHP Version: 7.3.0-beta-2
- Hosted locally on Laravel Valet

### Description:
Trying to `compact` a non-defined variable.

https://github.com/ARCANEDEV/LogViewer/blob/a8cd768e8ab4f2ec80d2d3208f34af2799c847c2/src/Http/Controllers/LogViewerController.php#L82-L89

### Steps To Reproduce:
Followed @arcanedev-maroc instructions in https://github.com/ARCANEDEV/LogViewer/issues/195#issuecomment-367388830
```bash
composer create-project laravel/laravel fresh-laravel && cd fresh-laravel
composer require arcanedev/log-viewer
// set LOG_CHANNEL=daily
php artisan log-viewer:publish
```
Added logging to route:
```php
Route::get('/', function () {
    Log::info('This is info log');

    return view('welcome');
});
```
- Visit URL to create some logs
- Visit log-viewer URL: http://fresh-laravel.test/log-viewer
- Click on the "Logs" link.  Get error: `compact(): Undefined variable: footer`

screen shot 2018-09-10 at 9 11 42 pm

### PR DESCRIPTION
**Pull request by drbyte**
Closes #234

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thanks a lot for your PR. 

I'm going to close it because i've fixed it for the upcoming PHP version.

More details about the issue: https://travis-ci.org/ARCANEDEV/LogViewer/jobs/442057444

**Comment by amirgee007** [comment]
how to fix this in laravel 5.6 with PHP 7.3?

Any idea?

**Comment by arcanedev-maroc** [comment]
Hi @amirgee007

Try to upgrade your laravel project into v5.7 or use PHP 7.2 instead

**Comment by amirgee007** [comment]
ok Thank you

**Pull request closed without merging**
